### ISSUE TITLE
Step on a bus adaper will cause game crash and that the player cant play on the server/world

### ISSUE THREAD

**Issue by Zhen-Bo** [grondag/facility#24]
When I was testing this mod
![1](https://user-images.githubusercontent.com/30999421/101930866-ac700600-3c13-11eb-9cb4-983c52a6d6f0.png)
I build this and step on it accidentally,and my game crash instantely.
when I reconnect the server it crash again because I am still on it.
Using facility-mc116-0.11.187 and both install on fabric 1.16.3 mc server and 1.16.3 fabric client

**Comment by grondag** [comment]
Please provide a crash log.

**Comment by Zhen-Bo** [comment]
It should be this
`---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 2020/12/12 上午 12:46
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at grondag.xm.modelstate.AbstractPrimitiveModelState.pos(AbstractPrimitiveModelState.java:575)
	at grondag.xm.modelstate.WorldToModelStateImpl.apply(WorldToModelStateImpl.java:76)
	at grondag.xm.modelstate.WorldToModelStateImpl.apply(WorldToModelStateImpl.java:44)
	at net.minecraft.class_2680.modelState(class_2680.java:544)
	at grondag.xm.api.block.XmBlockState.modelState(XmBlockState.java:68)
	at grondag.facility.transport.PipeBlock.method_9530(PipeBlock.java:118)
	at net.minecraft.class_4970$class_4971.method_26172(class_4970.java:786)
	at net.minecraft.class_4970$class_4971.method_26218(class_4970.java:782)
	at net.minecraft.class_4970.method_9549(class_4970.java:324)
	at net.minecraft.class_4970$class_4971.method_26194(class_4970.java:797)
	at net.minecraft.class_4970$class_4971.method_26220(class_4970.java:793)
	at baritone.pathing.movement.MovementHelper.isBlockNormalCube(MovementHelper.java:525)
	at baritone.pathing.movement.MovementHelper.canWalkOn(MovementHelper.java:303)
	at baritone.pathing.movement.MovementHelper.canWalkOn(MovementHelper.java:359)
	at baritone.pathing.movement.MovementHelper.canWalkOn(MovementHelper.java:355)
	at baritone.behavior.PathingBehavior.pathStart(PathingBehavior.java:382)
	at baritone.behavior.PathingBehavior.onTick(PathingBehavior.java:98)
	at baritone.event.GameEventHandler.lambda$onTick$0(GameEventHandler.java:61)
	at baritone.event.GameEventHandler$$Lambda$4873/1728083442.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at baritone.event.GameEventHandler.onTick(GameEventHandler.java:61)
	at net.minecraft.class_310.handler$zbb000$runTick(class_310.java:3374)
	at net.minecraft.class_310.method_1574(class_310.java:1500)
	at net.minecraft.class_310.method_1523(class_310.java:996)
	at net.minecraft.class_310.method_1514(class_310.java:656)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:168)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
	at me.deftware.client.framework.main.Main.main(Main.java:43)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at grondag.xm.modelstate.AbstractPrimitiveModelState.pos(AbstractPrimitiveModelState.java:575)
	at grondag.xm.modelstate.WorldToModelStateImpl.apply(WorldToModelStateImpl.java:76)
	at grondag.xm.modelstate.WorldToModelStateImpl.apply(WorldToModelStateImpl.java:44)
	at net.minecraft.class_2680.modelState(class_2680.java:544)
	at grondag.xm.api.block.XmBlockState.modelState(XmBlockState.java:68)
	at grondag.facility.transport.PipeBlock.method_9530(PipeBlock.java:118)
	at net.minecraft.class_4970$class_4971.method_26172(class_4970.java:786)
	at net.minecraft.class_4970$class_4971.method_26218(class_4970.java:782)
	at net.minecraft.class_4970.method_9549(class_4970.java:324)
	at net.minecraft.class_4970$class_4971.method_26194(class_4970.java:797)
	at net.minecraft.class_4970$class_4971.method_26220(class_4970.java:793)
	at baritone.pathing.movement.MovementHelper.isBlockNormalCube(MovementHelper.java:525)
	at baritone.pathing.movement.MovementHelper.canWalkOn(MovementHelper.java:303)
	at baritone.pathing.movement.MovementHelper.canWalkOn(MovementHelper.java:359)
	at baritone.pathing.movement.MovementHelper.canWalkOn(MovementHelper.java:355)
	at baritone.behavior.PathingBehavior.pathStart(PathingBehavior.java:382)
	at baritone.behavior.PathingBehavior.onTick(PathingBehavior.java:98)
	at baritone.event.GameEventHandler.lambda$onTick$0(GameEventHandler.java:61)
	at baritone.event.GameEventHandler$$Lambda$4873/1728083442.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at baritone.event.GameEventHandler.onTick(GameEventHandler.java:61)
	at net.minecraft.class_310.handler$zbb000$runTick(class_310.java:3374)

-- Affected level --
Details:
	All players: 1 total; [class_746['Paver_LuL'/2406, l='ClientLevel', x=-251.06, y=69.18, z=-170.75]]
	Chunk stats: Client Chunk Cache: 729, 635
	Level dimension: minecraft:overworld
	Level spawn location: World: (-258,65,-86), Chunk: (at 14,4,10 in -17,-6; contains blocks -272,0,-96 to -257,255,-81), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 3491693 game time, 3560764 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:617)
	at net.minecraft.class_310.method_1587(class_310.java:2183)
	at net.minecraft.class_310.method_1514(class_310.java:679)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:168)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
	at me.deftware.client.framework.main.Main.main(Main.java:43)

-- System Details --
Details:
	Minecraft Version: 1.16.3
	Minecraft Version ID: 1.16.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 5057346368 bytes (4823 MB) / 8589934592 bytes (8192 MB) up to 8589934592 bytes (8192 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		appleskin: AppleSkin 1.0.11
		artifice: Artifice 0.14.4+1.16.3
		autoconfig1u: Auto Config v1 Updated 3.2.2
		baritoe: Baritone 1.6.1
		bbor: BoundingBoxOutlineReloaded 2.4-1.16.3
		beachslimes: Beach Slimes 2.1.0+mc1.16.1
		bigbuckets: Big Buckets 2.0.0
		blue_endless_jankson: jankson 1.2.0
		can-i-mine-this-block: cAn i MiNe thIS bLOCk? 1.0.2
		cardinal-components-base: Cardinal Components API (base) 2.5.0
		cardinal-components-entity: Cardinal Components API (entities) 2.5.0
		carpet: Carpet Mod in Fabric 1.4.20
		chainmail: Chainmail 0.5.0
		chesttracker: Chest Tracker 0.7.9
		cloth-api: Cloth API 1.4.9
		cloth-armor-api-v1: Cloth Armor API v1 1.4.9
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.4.9
		cloth-common-events-v1: Cloth Common Events v1 1.4.9
		cloth-config2: Cloth Config v4 4.8.2
		cloth-datagen-api-v1: Cloth Datagen v1 1.4.9
		cloth-durability-bar-api-v1: Cloth Durability Bar API v1 1.4.9
		cloth-dynamic-registry-api-v1: Cloth Dynamic Registry API v1 1.4.9
		cloth-scissors-api-v1: Cloth Scissors API v1 1.4.9
		cloth-utils-v1: Cloth Utils v1 1.4.9
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		crowdin-translate: CrowdinTranslate 1.2
		csb: Custom Selection Box Fabric 5.0.2
		diggusmaximus: Diggus Maximus 1.4.2-1.16.3
		easiercrafting: EasierCrafting 1.16.4-fabric0.25.1-1.6.6
		easiervillagertrading: EasierVillagerTrading 1.16-fabric0.13.1-1.5.2
		emc: EMC Framework 2.0.0
		exotic-art-core: Exotic Art Core Content Pack 1.0.362
		exotic-art-tech: Exotic Art Tech Pack 1.2.362
		exotic-matter: Exotic Matter 2.10.362
		expandedstorage: ExpandedStorage 5.6.30
		fabric: Fabric API 0.25.4+1.16
		fabric-api-base: Fabric API Base 0.2.0+9f0fb4b83a
		fabric-biome-api-v1: Fabric Biome API (v1) 3.0.0+8367596d3a
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea893a
		fabric-command-api-v1: Fabric Command API (v1) 1.0.9+a4467d2a3a
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d308363a
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f3a
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea8663a
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d3a
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.1+f8ac1db23a
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b3a
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.3+a4467d2a3a
		fabric-item-api-v1: Fabric Item API (v1) 1.2.0+f8ac1db23a
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.1+a4467d2a3a
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c63a
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c53a
		fabric-language-kotlin: Fabric Language Kotlin 1.4.0+build.1
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+74cc3b203a
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+432ea1883a
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce993a
		fabric-models-v0: Fabric Models (v0) 0.1.1+f8ac1db23a
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b3a
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f95
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.2+a89534ab3a
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.1+a4467d2a3a
		fabric-particles-v1: fabric-particles-v1 0.2.2+fb0d9b0e3a
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.6.1+a4467d2a3a
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.3.3+a4467d2a3a
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.3+a4467d2a3a
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.0+f8ac1db23a
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+f8ac1db23a
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.12+f8ac1db23a
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.1+f8ac1db23a
		fabric-rendering-v1: Fabric Rendering (v1) 1.3.1+f8ac1db23a
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.3.1+facf3bbf3a
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+872498413a
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.0+f8ac1db23a
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.0.3+ac8e8c593a
		fabric-textures-v0: Fabric Textures (v0) 1.0.5+a4467d2a3a
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.5+c93221003a
		fabricloader: Fabric Loader 0.10.6+local
		facility: Facility 0.11.187
		fermion: Fermion 2.6.206
		fermion-gui: Fermion GUI 2.4.206
		fermion-modkeys: Fermion Modifier Keys 1.9.206
		fermion-orientation: Fermion Orientation 1.1.205
		fermion-varia: Fermion Varia 2.4.206
		fluidity: Fluidity 0.15.195
		fonthack: Font Hack 2.3.44
		gbfabrictools: GBfabrictools 1.3.2+1.16.4
		greater_eye: Greater Eye of Ender 1.1.3
		imblocker: IMBlockerFabric 1.0.10
		inventoryhud: Inventory HUD + 3.1.2
		inventoryprofiles: Inventory Profiles 0.4.2
		invtrashslot: InvTrashSlot 1.0.2
		iron-jetpacks: Iron Jetpacks 0.2.6
		itemscroller: Item Scroller 0.15.0-dev.20200912.221805
		jankson: Jankson 3.0.1+j1.2.0
		kyrptconfig: Kytpt Config 1.1.4-1.16
		leaf-decay: Leaf Decay 1.2.0-1.16.1
		libblockattributes: LibBlockAttributes 0.8.1
		libblockattributes_core: LibBlockAttributes (Core) 0.8.1
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.8.1
		libblockattributes_items: LibBlockAttributes (Items) 0.8.1
		libcd: LibCapableData 2.5.0+1.16.1
		libgui: LibGui 3.2.1+1.16.3
		lightoverlay: Light Overlay 5.5.3
		litematica: Litematica 0.0.0-dev.20200920.161640
		malilib: MaLiLib 0.10.0-dev.21+arne.1
		megane: megane 3.0.7+1.16.4
		megane-api: megane-api 3.0.7+1.16.4
		megane-impl: megane-impl 3.0.7+1.16.4
		megane-runtime: megane-runtime 3.0.7+1.16.4
		minecraft: Minecraft 1.16.3
		mm: Manningham Mills 2.1
		modmenu: Mod Menu 1.14.6+build.31
		optifabric: OptiFabric 1.6.2
		org_jetbrains_annotations: annotations 20.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.0
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.0
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.3.9
		parchment: Parchment 1.0.2+1.15.2
		polymorph: Polymorph 0.0.5-1.16.3
		reborncore: Reborn Core 4.5.0+build.84
		render-layer-trans: Render Layer Transformer 1.16.2-1.0.0
		ringsofascension: Rings of Ascension 1.0.7
		roughlyenoughitems: Roughly Enough Items 5.6.0
		roughlyenoughitems-api: REI (API) 5.6.0
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.6.0
		roughlyenoughitems-runtime: REI (Runtime) 5.6.0
		special-circumstances: Special Circumstances 1.7.206
		team_reborn_energy: Energy 0.1.0
		techreborn: Tech Reborn 3.6.1+build.143
		torcherino: Torcherino 2.12.69
		torohealth: ToroHealth Damage Indicators 1.16.4-fabric-2
		trade: Trade 1.1.2
		trinkets: Trinkets 2.6.7
		tweakeroo: Tweakeroo 0.10.0-dev.20200913.175041
		voxelmap: VoxelMap 1.10.11
		waila: Hwyla 1.9.22
		worldedit: WorldEdit 7.2.0-rc-01+81f978e
	Launched Version: 1.16.3-Aristois
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 457.30, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, fabric/autoconfig1u, fabric/bbor, bbor (incompatible), fabric/carpet, fabric/chesttracker, fabric/cloth-config2, fabric/emc, fabric/fabric, fabric/fabric-api-base, fabric/fabric-biome-api-v1, fabric/fabric-blockrenderlayer-v1, fabric/fabric-command-api-v1, fabric/fabric-containers-v0, fabric/fabric-content-registries-v0, fabric/fabric-crash-report-info-v1, fabric/fabric-events-interaction-v0, fabric/fabric-events-lifecycle-v0, fabric/fabric-game-rule-api-v1, fabric/fabric-item-api-v1, fabric/fabric-item-groups-v0, fabric/fabric-key-binding-api-v1, fabric/fabric-keybindings-v0, fabric/fabric-lifecycle-events-v1, fabric/fabric-loot-tables-v1, fabric/fabric-mining-levels-v0, fabric/fabric-models-v0, fabric/fabric-networking-blockentity-v0, fabric/fabric-networking-v0, fabric/fabric-object-builder-api-v1, fabric/fabric-object-builders-v0, fabric/fabric-registry-sync-v0, fabric/fabric-renderer-api-v1, fabric/fabric-renderer-indigo, fabric/fabric-renderer-registries-v1, fabric/fabric-rendering-data-attachment-v1, fabric/fabric-rendering-fluids-v1, fabric/fabric-rendering-v0, fabric/fabric-rendering-v1, fabric/fabric-resource-loader-v0, fabric/fabric-screen-handler-api-v1, fabric/fabric-tag-extensions-v0, fabric/fabric-textures-v0, fabric/fabric-tool-attribute-api-v1, fabric/fabricloader, fabric/itemscroller (incompatible), fabric/jankson, fabric/libgui, fabric/litematica (incompatible), fabric/malilib (incompatible), fabric/mm, fabric/modmenu, fabric/roughlyenoughitems, fabric/roughlyenoughitems-runtime, fabric/tweakeroo (incompatible), fabric/voxelmap (incompatible), fabric/appleskin (incompatible), file/XeKr 方纹淡彩16_17b.zip, file/XK-ClearLavaTexturePack.zip (incompatible), fabric/easiervillagertrading, fabric/expandedstorage, fabric/imblocker, fabric/inventoryhud, fabric/leaf-decay, fabric/lightoverlay (incompatible), fabric/optifabric, fabric/torcherino, fabric/worldedit (incompatible), fabric/artifice, fabric/bigbuckets (incompatible), fabric/fabric-language-kotlin, fabric/greater_eye, fabric/inventoryprofiles, fabric/invtrashslot, fabric/iron-jetpacks (incompatible), fabric/libblockattributes, fabric/libblockattributes_core, fabric/libblockattributes_fluids, fabric/libblockattributes_items, fabric/reborncore, fabric/ringsofascension, fabric/team_reborn_energy, fabric/techreborn, fabric/trade, fabric/trinkets, fabric/diggusmaximus, fabric/torohealth
	Current Language: 繁體中文 (台灣)
	CPU: 8x Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
	OptiFine Version: OptiFine_1.16.3_HD_U_G3
	OptiFine Build: 20200916-082411
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 457.30
	OpenGlRenderer: GeForce GTX 1050 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8`

**Comment by grondag** [comment]
Facility cannot be compatible with OptiFine because it does not support the Fabric Rendering API.  Canvas Renderer is a compatible alternative but with fewer features at this time.

I'm also not able to support older version of Minecraft or Fabric API.  This seems to be fine on MC 1.16.4 and latest versions of Fabric API and my mods.
